# SPDX-FileCopyrightText: 2022-2025 Objectionary.com
# SPDX-License-Identifier: MIT
name: cargo-deny
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          log-level: warn
